# Generated by Django 4.1.7 on 2023-02-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="content",
            field=models.TextField(default="", verbose_name="본문"),
        ),
    ]
