# Generated by Django 4.1.7 on 2023-02-25 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edus", "0002_education_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="content",
        ),
    ]
