# Generated by Django 4.1.7 on 2023-02-17 09:52

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="공연 제목")),
                (
                    "cover",
                    models.ImageField(
                        upload_to=functools.partial(
                            common.utils._update_filename,
                            *(),
                            **{"hash": True, "path": "concerts"}
                        ),
                        verbose_name="공연 대표 이미지",
                    ),
                ),
                (
                    "is_banner",
                    models.BooleanField(default=False, verbose_name="메인 페이지 배너 사용 유무"),
                ),
                ("date", models.DateField(verbose_name="공연 일자")),
                ("place", models.CharField(max_length=50, verbose_name="공연 장소")),
                ("ticket", models.CharField(max_length=50, verbose_name="티켓 가격 정보")),
                ("context", models.TextField(default="")),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "공연 리스트",
            },
        ),
    ]
