# Generated by Django 4.1.7 on 2023-02-28 01:25

import common.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="공연 제목")),
                (
                    "cover",
                    models.ImageField(
                        upload_to=functools.partial(
                            common.utils._update_filename,
                            *(),
                            **{"hash": True, "path": "concerts"}
                        ),
                        verbose_name="공연 대표 이미지",
                    ),
                ),
                (
                    "is_banner",
                    models.BooleanField(default=False, verbose_name="메인 페이지 배너 사용 유무"),
                ),
                ("date", models.DateTimeField(verbose_name="공연 일자")),
                ("place", models.CharField(max_length=50, verbose_name="공연 장소")),
                ("booking_url", models.CharField(max_length=250, verbose_name="예매 링크")),
                ("ticket", models.CharField(max_length=50, verbose_name="티켓 가격 정보")),
                ("content", models.TextField(default="", verbose_name="본문")),
            ],
            options={
                "verbose_name_plural": "공연 리스트",
            },
        ),
    ]
