# Generated by Django 4.1.7 on 2023-02-17 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0002_concert_booking_url_alter_concert_context"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concert",
            old_name="context",
            new_name="content",
        ),
    ]
