# Generated by Django 4.1.7 on 2023-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concerts", "0004_alter_concert_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="date",
            field=models.DateTimeField(verbose_name="공연 일자"),
        ),
    ]
