# Generated by Django 4.1.7 on 2023-02-17 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="title",
            field=models.CharField(max_length=50, verbose_name="공지 제목"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="visited",
            field=models.PositiveIntegerField(default=0, verbose_name="방문자 횟수"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
    ]
