# Generated by Django 4.1.7 on 2023-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0002_alter_notice_title_alter_notice_visited_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="visited",
            field=models.PositiveIntegerField(default=0, verbose_name="방문 횟수"),
        ),
    ]
