# Generated by Django 4.1.7 on 2023-02-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0003_alter_notice_visited"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="고정 여부"),
        ),
    ]
