# Generated by Django 4.1.7 on 2023-02-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notices", "0004_notice_is_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="공지사항"),
        ),
    ]
