# Generated by Django 4.1.7 on 2023-02-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="문의 제목")),
                ("contact", models.CharField(max_length=254, verbose_name="문의자 연락처")),
                (
                    "type",
                    models.CharField(
                        choices=[("concert", "공연 문의"), ("edu", "교육 문의")],
                        max_length=20,
                        verbose_name="문의 종류",
                    ),
                ),
                ("content", models.TextField(default="", verbose_name="문의 내용")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
