# Generated by Django 4.1.7 on 2023-02-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qnas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name_plural": "문의 리스트"},
        ),
        migrations.AddField(
            model_name="question",
            name="person",
            field=models.CharField(default="", max_length=254, verbose_name="문의자 성함"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[("concert", "공연 문의"), ("edu", "교육 문의"), ("etc", "기타")],
                max_length=20,
                verbose_name="문의 종류",
            ),
        ),
    ]
