# Generated by Django 4.1.7 on 2023-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qnas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_answered",
            field=models.BooleanField(default=False, verbose_name="답변 여부"),
        ),
    ]
